spring:
  application:
    name: redis-springboot-demo

  ##### Redis Configuration
  redis:
    host: localhost
    port: 6379
  # ===========================
  # Database Configuration
  # ===========================
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    password:
  # ===========================
  # H2 Console Configuration
  # ===========================
  h2:
    console:
      enabled: true
      path: /h2-console
  # ===========================
  # JPA / Hibernate Configuration
  # ===========================
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


# ===========================
# Stream Related Configuration
# ===========================

redis-stream:
  stream-key: purchase_event_queue

# ===========================
# Logging
# ===========================

logging:
  level:
    org.springframework.data.redis: error
    org.springframework.cache: debug

# ===========================
# Actuator Management
# ===========================

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        liveness:
          - redis
          - redisStream
        readiness:
          - redis
          - redisStream